FROM registry.access.redhat.com/ubi9/ubi-minimal:9.4
WORKDIR /work/
RUN chown 1001 /work \
    && chmod "g+rwX" /work \
    && chown 1001:root /work
COPY --chown=1001:root target/*-runner /work/application
COPY --chown=1001:root wait-for-it.sh /work/wait-for-it.sh
EXPOSE 8081
USER 1001
ENTRYPOINT ["/work/wait-for-it.sh", "keycloak:8080", "--timeout=60", "--", "./application", "-Dquarkus.http.host=0.0.0.0", "-Dquarkus.http.port=8081"]